# Site settings
title: Shaun David Ellis
email: shaun@sdellis.com
description: > # this means to ignore newlines until "baseurl:"
  Thoughtful UX Developer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sdellis.com" # the base hostname & protocol for your site
twitter_username: sdellis
github_username:  sdellis

collections:
  labs:
    output: true

defaults:
  - scope:
      path: ""
      type: labs
    values:
      layout: experiment

# Build settings
markdown: kramdown
